name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          path: ${{ github.event.repository.name }}
      - name: Update permissions
        run: chmod a+x ${{ github.event.repository.name }}/.github/scripts/deploy.sh
        shell: bash
      - name: Deploy artifact
        env:
          DEPLOY_SERVER: ${{ vars.DEPLOY_SERVER }}
          SSH_USER: ${{ vars.SSH_USER }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_PATH: ${{ github.repository }}
          REPO_NAME: ${{ github.event.repository.name }}
          TAG: ${{ github.ref_name }}
          SSH_PRIVATE: ${{ secrets.SSH_PRIVATE }}
        run: ${{ github.event.repository.name }}/.github/scripts/deploy.sh
        shell: bash
